apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-app-deployment
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular-app
  template:
    metadata:
      labels:
        app: angular-app
    spec:
      containers:
        - name: angular-app
          image: mehdihammami244/pfe-frontend:latest
          ports:
            - containerPort: 85
          volumeMounts:
          - name: config-volume
            mountPath: /usr/share/nginx/html/assets/config.json
            subPath: config.json
      volumes:
      - name: config-volume
        configMap:
          name: angular-config
