# frontend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-app
spec:
  selector:
    matchLabels:
      app: angular-app
  template:
    metadata:
      labels:
        app: angular-app
    spec:
      containers:
      - name: frontend
        image: mehdihammami244/pfefrontend
        ports:
        - containerPort: 80

---
# frontend-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: angular-app
spec:
  type: LoadBalancer
  selector:
    app: angular-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
